### PR TITLE
Fix: Move Instatus to Notification Workspace and Register It as a Notification Channel

### LINKED ISSUE #1047: InStatus Channel Seems Gone after v1.15.2
**Describe the bug**
Got this error when enabling instatus notification type:
```
Notifications type is not allowed (instatus)
```

**To Reproduce**
Use this config:
```
probes:
- id: probe-01
  requests:
    - url: http://github.com/asdasda

- id: probe-02
  requests:
    - url: http://github.com

notifications:
- id: internal-instatus
  type: instatus
  data:
    apiKey: xxx
    pageID: xxx
```

I think, It appears that the instatus notification feature stopped working after this refactor https://github.com/hyperjumptech/monika/pull/1019/files#diff-a4c29782d941cc4d914b2715f202ac340a4ef1988c812c04e38e8f8480225a69

### PR DESCRIPTION
**Pull request by haricnugraha**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
Move Instatus to notification workspace and register It as a notification channel. Will resolve #1047. 

## How did you implement / how did you fix it  
1.  Move Instatus code to notification workspace
2. Register it in `channels` variable

## How to test  
1. Run Monika with Instatus notification
2. Make the website in your probe down (make sure it is your website)
3. Make it up again

## Notes
There is a bug where Monika sends two notification if the probe has 2 alerts. And it will only recover one. The bug appears in version 1.15.1, so I didn't solve it in this PR. 

## Video
https://github.com/hyperjumptech/monika/assets/15191978/e96aba8d-8371-48e7-bdc2-d63a7a2b1ae6

### CODE REVIEW

File: packages/notification/channel/instatus/database.ts [hunk 1]
```diff
@@ -54,9 +59,25 @@ export async function findIncident({
...
+  if (!db) {
+    db = await open({
+      filename: dbPath,
+      mode: sqlite3.OPEN_READWRITE | sqlite3.OPEN_CREATE,
+      driver: sqlite3.Database,
+    })
+  }
+
+  return db
+}
```
Comment (nicnocquee) [inline packages/notification/channel/instatus/database.ts:83]: should this be here? or should it be in like common directory?

**Review by nicnocquee — APPROVED** [review]

File: packages/notification/channel/instatus/database.ts (hunk 1 above)
Comment (haricnugraha) [reply packages/notification/channel/instatus/database.ts:83]: IMO, only Instatus will use this code for now. So it would be better if we just put all the Instatus related code in one directory. If in the future other channel need it, the developer can extract the functionality to make it reusable

**Review by sapiderman — APPROVED** [review]
works for me!

image
