### PR TITLE
fix: handle get rss feed using getStaticProps

### LINKED ISSUE #544: The Articles in Docs does not appear
**Describe the bug**

Seems like the articles cannot be loaded. 

**To Reproduce**
1. Go to [Articles page](https://monika.hyperjump.tech/articles)

**Expected behavior**
Articles showed up

**Screenshots**

Screenshot 2021-12-21 at 10 16 34

**Desktop (please complete the following information):**
 - Google Chrome
 - macOS Monterey

**Additional context**
Probably it's better to build the articles page during build time.

### PR DESCRIPTION
**Pull request by dennypradipta**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
This PR fixes #544 where the articles are not appearing.

## How did you implement / how did you fix it  
Move the handler to getStaticProps for speed, and handle if there is no articles

## How to test  
1. cd docs
2. npm run dev
3. Go to localhost:3000/articles

### CODE REVIEW

File: docs/src/pages/articles.js [hunk 1]
```diff
@@ -67,7 +65,41 @@ export default function ArticlesPage() {
...
+    const { data } = await axios({
+      method: 'GET',
+      url: 'https://medium.com/feed/hyperjump-tech',
+      headers: {
+        'Access-Control-Allow-Origin': '*',
+        'Content-Type': 'application/rss+xml',
+      },
+    })
+
+    if (!data) {
```
Comment (samsunoor) [inline docs/src/pages/articles.js:79]: we can throw exception here to short circuit to the same return statement in catch block.

**Review by samsunoor — APPROVED** [review]

**Review by sapiderman — APPROVED** [review]
merge!

File: docs/src/pages/articles.js (hunk 1 above)
Comment (dennypradipta) [reply docs/src/pages/articles.js:79]: Whoopsie. Didn't think about that. Should be fixed
