### PR TITLE
Fix: mailgun notification handle node 18

### LINKED ISSUE #1104: Mailgun notification not working in node 18
**Describe the bug**
Running monika with mailgun notification and node 18 will show error `fetch failed`. Confirmed from this issue https://github.com/mailgun/mailgun.js/issues/275, it is due to the node.js v18 by default enables experimental global fetch API `node-fetch`

**To Reproduce**
1. use node v18.x.x . confirm it by running `node -v`
2. set mailgun notification like in the [docs](https://monika.hyperjump.tech/guides/notifications#mailgun)
3. run monika normally with `npm start`

**Expected behavior**
monika running normally without error

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: confirmed on Ubuntu 22 & Mac OS Monterey

### PR DESCRIPTION
**Pull request by raosan**
# Monika Pull Request (PR)

## What feature/issue does this PR add
1. Fix #1104 by changing how to send mailgun notification from using npm library to using http request.

## How did you implement / how did you fix it
1. remove `mailgun.js` npm package
2. extract `getContent` function
3. change implementation to use `sendHttpRequest` in `send` function
4. add `sendWithCustomContent` function to support [Neosnse](https://neosense.bgnlab.id/)

## How to test
1. add config for mailgun notification
5. run monika with node 18
6. monika running without error
7. get email that monika is starting 
Inked2

### CODE REVIEW

**Review by nicnocquee — APPROVED** [review]

File: packages/notification/channel/mailgun.ts [hunk 1]
```diff
@@ -22,19 +22,27 @@
...
 import type { NotificationMessage } from '.'
 import Mailgen from 'mailgen'
+import { sendHttpRequest } from '../utils/http'
 
-type NotificationData = {
+export type NotificationData = {
   apiKey: string
   domain: string
   recipients: string[]
   username?: string
```
Comment (nicnocquee) [inline packages/notification/channel/mailgun.ts:35]: it seems like for mailgun the username must always be `api` https://documentation.mailgun.com/en/latest/api-intro.html#authentication-1. So i think it's better to remove this.

**Review by nicnocquee — CHANGES_REQUESTED** [review]

**Review by nicnocquee — APPROVED** [review]

File: packages/notification/channel/mailgun.ts [hunk 2]
```diff
@@ -22,17 +22,24 @@
...
-import Mailgun from 'mailgun.js'
-import formData from 'form-data'
+import FormData from 'form-data'
 import Joi from 'joi'
 import type { NotificationMessage } from '.'
 import Mailgen from 'mailgen'
+import { sendHttpRequest } from '../utils/http'
 
-type NotificationData = {
+export type NotificationData = {
```
Comment (haricnugraha) [inline packages/notification/channel/mailgun.ts:31]: Could you elaborate why it needs to be exported?

File: packages/notification/channel/mailgun.ts [hunk 3]
```diff
@@ -22,17 +22,24 @@
...
   apiKey: string
   domain: string
   recipients: string[]
-  username?: string
+}
+
+export type Content = {
```
Comment (haricnugraha) [inline packages/notification/channel/mailgun.ts:37]: Could you elaborate why it needs to be exported?

File: packages/notification/channel/teams.ts [hunk 4]
```diff
@@ -26,7 +26,7 @@ import Joi from 'joi'
 import { sendHttpRequest } from '../utils/http'
 import type { NotificationMessage } from '.'
 
-type NotificationData = {
+export type NotificationData = {
```
Comment (haricnugraha) [inline packages/notification/channel/teams.ts:29]: Could you elaborate why it needs to be exported?

File: packages/notification/channel/mailgun.ts [hunk 5]
```diff
@@ -42,17 +49,70 @@ export const validator = Joi.object().keys({
...
 export const send = async (
-  { apiKey: key, domain, recipients, username = 'api' }: NotificationData,
-  { body, subject }: NotificationMessage
+  notificationData: NotificationData,
+  notificationMessage: NotificationMessage
+): Promise<void> => {
+  await _send(notificationData, notificationMessage)
+}
+
+export const sendWithCustomContent = async (
```
Comment (haricnugraha) [inline packages/notification/channel/mailgun.ts:96]: Could you elaborate why it needs to be exported?

Comment (raosan) [reply packages/notification/channel/mailgun.ts:96]: Need to be exported to be used in neosense. Also, if not exported it will get error typescript 
```
sendWithCustomContent is declared but its value is never read.
```

File: packages/notification/channel/mailgun.ts (hunk 3 above)
Comment (raosan) [reply packages/notification/channel/mailgun.ts:37]: since `sendWithCustomContent(notificationData, content)` will be used by neosene, then the type of the parameter need to be imported there to be exactly the same

File: packages/notification/channel/teams.ts (hunk 4 above)
Comment (raosan) [reply packages/notification/channel/teams.ts:29]: since `sendWithCustomContent(notificationData, content)` will be used by neosene, then the type of the parameter need to be imported there to be exactly have same type

File: packages/notification/channel/mailgun.ts (hunk 2 above)
Comment (raosan) [reply packages/notification/channel/mailgun.ts:31]: same with other, need to be exported to be used in neosense

File: test/plugins/prometheus/index.test.ts [hunk 6]
```diff
@@ -42,7 +43,7 @@ describe('Prometheus plugin', () => {
       )
       .it('runs Prometheus metric server', async (ctx) => {
         // act
-        const res = await fetch('http://localhost:4444/metrics')
+        const res = await axios.get('http://localhost:4444/metrics')
```
Comment (haricnugraha) [inline test/plugins/prometheus/index.test.ts:46]: Don't change this to Axios. Because, there is an effort to change from Axios to fetch in this PR https://github.com/hyperjumptech/monika/pull/1094. Could you elaborate why you need to change this?

Comment (raosan) [reply test/plugins/prometheus/index.test.ts:46]: I think #1094 is to change the implementation when probing. But this axios is used for test. it's not related, right?

Comment (raosan) [reply test/plugins/prometheus/index.test.ts:46]: this is the root cause of https://github.com/hyperjumptech/monika/pull/1110 
maybe need to merge it first?

Comment (haricnugraha) [reply test/plugins/prometheus/index.test.ts:46]: Ok

**Review by haricnugraha — APPROVED** [review]
