### PR TITLE
fixed(notif): Add termination notif

### LINKED ISSUE #246: Send notification on Monika termination
As part of our plan to refactor Monika, add send notification on monika termination listener.

The notification:

- title: Monika terminated.
- body: Monika is no longer running in <ip_address>.

### PR DESCRIPTION
**Pull request by ilmiawan**
# Monika PR
Fix #246 Send notification on Monika termination
## What issue this PR is trying to solve
Currently there is no notification when monika is terminated
## How this PR solve the issue
By adding send termination notif and trigger it when Monika is terminated
## How to test
1. set notifications on monika configuration
2. run monika
3. kill monika using `ctrl + c`

### CODE REVIEW

File: src/components/notification/termination.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    .filter((notif) => notif.type === 'monika-notif')
+    .map((notif) => notif.data as MonikaNotifData)
+    .map((data) => monikaNotificationSender({ data, body, status }))
+
+  const workplaceNotification = notifications
+    .filter((notif) => notif.type === 'workplace')
+    .map((notif) => notif.data as WorkplaceData)
+    .map((data) => workplaceNotificationSender({ data, body }))
+
+  const desktopNotification = notifications
```
Comment (dennypradipta) [inline src/components/notification/termination.ts:93]: image
Wrong title for desktop notification. Probably you should check other channels too

**Review by dennypradipta — CHANGES_REQUESTED** [review]

File: src/components/notification/termination.ts (hunk 1 above)
Comment (raosan) [reply src/components/notification/termination.ts:93]: check for those who has `status` in the params. Seems like it need to be changed in the individual send functions in `components/notification/index.ts`. for example monika-notif:
```
case 'monika-notif': {
         return sendMonikaNotif({
           ...
            body: {
              type: status === 'DOWN' ? 'incident' : 'recovery',
              ...
            },
          }
```

Comment (ilmiawan) [reply src/components/notification/termination.ts:93]: done.

**Review by nicnocquee — APPROVED** [review]

**Review by dennypradipta — APPROVED** [review]
