### PR TITLE
feature(config): [297] fix monika json generated

### LINKED ISSUE #297: HAR importer is missing headers and body
**Describe the bug**
The generated monika.json when converting from HAR does not include headers and body of request.

**To Reproduce**

Use the following HAR:

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2021-07-27T10:09:14.827Z",
        "id": "page_2",
        "title": "https://namb.ch/api/admin/login",
        "pageTimings": {
          "onContentLoad": 625.334000098519,
          "onLoad": 683.750000083819
        }
      }
    ],
    "entries": [
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "connection": "2315686",
        "pageref": "page_2",
        "request": {
          "method": "POST",
          "url": "https://namb.ch/api/admin/login",
          "httpVersion": "http/2.0",
          "headers": [
            {
              "name": ":method",
              "value": "POST"
            },
            {
              "name": ":authority",
              "value": "namb.ch"
            },
            {
              "name": ":scheme",
              "value": "https"
            },
            {
              "name": ":path",
              "value": "/api/admin/login"
            },
            {
              "name": "content-length",
              "value": "46"
            },
            {
              "name": "pragma",
              "value": "no-cache"
            },
            {
              "name": "cache-control",
              "value": "no-cache"
            },
            {
              "name": "sec-ch-ua",
              "value": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "upgrade-insecure-requests",
              "value": "1"
            },
            {
              "name": "origin",
              "value": "https://namb.ch"
            },
            {
              "name": "content-type",
              "value": "application/x-www-form-urlencoded"
            },
            {
              "name": "user-agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
            },
            {
              "name": "accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
            },
            {
              "name": "sec-fetch-site",
              "value": "same-origin"
            },
            {
              "name": "sec-fetch-mode",
              "value": "navigate"
            },
            {
              "name": "sec-fetch-user",
              "value": "?1"
            },
            {
              "name": "sec-fetch-dest",
              "value": "document"
            },
            {
              "name": "referer",
              "value": "https://namb.ch/admin"
            },
            {
              "name": "accept-encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "accept-language",
              "value": "en-GB,en-US;q=0.9,en;q=0.8"
            },
            {
              "name": "cookie",
              "value": "_fbp=fb.1.1624520390835.1717829411; _gid=GA825140508.1627380527; _gat_gtag_UA_89898_8=1; _ga_AAAAA=GS1.1.1.26.1.1.0; _ga=1.1"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "_fbp",
              "value": "fb.1.1624520390835.1717829411",
              "path": "/",
              "domain": ".namb.ch",
              "expires": "2021-10-03T11:34:02.000Z",
              "httpOnly": false,
              "secure": false,
              "sameSite": "Lax"
            },
            {
              "name": "_gid",
              "value": "GA825140508.1627380527",
              "path": "/",
              "domain": ".namb.ch",
              "expires": "2021-07-28T10:09:02.000Z",
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "_gat_gtag_UA_89898_8",
              "value": "1",
              "path": "/",
              "domain": ".namb.ch",
              "expires": "2021-07-27T10:09:46.000Z",
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "_ga_AAAAA",
              "value": "GS1.1.1.26.1.1.0",
              "path": "/",
              "domain": ".namb.ch",
              "expires": "2023-07-27T10:09:02.000Z",
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "_ga",
              "value": "1.1",
              "path": "/",
              "domain": ".namb.ch",
              "expires": "2023-07-27T10:09:02.000Z",
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": -1,
          "bodySize": 46,
          "postData": {
            "mimeType": "application/x-www-form-urlencoded",
            "text": "email=myemail&password=mypass",
            "params": [
              {
                "name": "email",
                "value": "myemail"
              },
              {
                "name": "password",
                "value": "mypassword"
              }
            ]
          }
        },
        "response": {
          "status": 307,
          "statusText": "",
          "httpVersion": "http/2.0",
          "headers": [
            {
              "name": "server",
              "value": "nginx/1.14.0 (Ubuntu)"
            },
            {
              "name": "date",
              "value": "Tue, 27 Jul 2021 10:09:15 GMT"
            },
            {
              "name": "set-cookie",
              "value": "token=sometoken; Max-Age=604800; Path=/; Expires=Tue, 27 Jul 2021 10:19:19 GMT; HttpOnly; Secure"
            },
            {
              "name": "location",
              "value": "/admin/dashboard"
            }
          ],
          "cookies": [
            {
              "name": "token",
              "value": "sometoken",
              "path": "/",
              "domain": "namb.ch",
              "expires": "2021-08-03T10:09:14.827Z",
              "httpOnly": true,
              "secure": true
            }
          ],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "/admin/dashboard",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 323,
          "_error": null
        },
        "serverIPAddress": "139.59.151.179",
        "startedDateTime": "2021-07-27T10:09:14.823Z",
        "time": 165.16699991188943,
        "timings": {
          "blocked": 6.083999902211129,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0.125,
          "wait": 153.91600003445893,
          "receive": 5.041999975219369,
          "_blocked_queueing": 4.37499990221113
        }
      }
    ]
  }
}

```

Then run `monika --create-config --har <path to the har>`

**Expected behavior**
The generated monika.json should have all the headers and the request body

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.4.1

### PR DESCRIPTION
**Pull request by ilmiawan**
# Monika Pull Request (PR)  
Fix #297 
## What feature/issue does this PR add  
The generated monika.json when converting from HAR does not include headers and body of request.

## How did you implement / how did you fix it  
add header and body parser and copy it to monika.json file generated

## How to test  
1. copy har file example from the issue #297 to `copy_example.har` file
2. run `./bin/run --create-config --har copy_example.har`
3. check generated monika.json, it should have headers and body filled.

Screen Shot 2021-07-27 at 20 04 25

### CODE REVIEW

File: src/components/config/parse-har.ts [hunk 1]
```diff
@@ -25,6 +25,33 @@
...
+  })
+  return obj
+}
+
+const parsePostData = (postData: any) => {
+  if (!postData) {
+    return {}
+  }
+
+  if (postData.mimeType === 'application/json') {
```
Comment (gsukanto) [inline src/components/config/parse-har.ts:48]: Do we need to prepare `multipart/form-data` mime type too?

**Review by gsukanto — APPROVED** [review]

**Review by sapiderman — APPROVED** [review]

File: src/components/config/parse-har.ts (hunk 1 above)
Comment (nicnocquee) [reply src/components/config/parse-har.ts:48]: yeah, but let's support json first for now.
