### PR TITLE
Monika doesn't save requests to local db and can't send report to Symon

### LINKED ISSUE #871: Monika doesn't save requests to local db and can't send report to Symon
`getContext` doesn't work if initialized in global, it must be initialized inside the `doProbe` function.

Screen Shot 2022-09-02 at 14 00 07

~And the flag `verboseLogs` will always return `undefined` since the available verbose's flags are either `verbose` or `keep-verbose-logs`.~

### PR DESCRIPTION
**Pull request by kevin-hyperjump**
This PR fixes #871

### CODE REVIEW

File: src/looper/index.ts [hunk 1]
```diff
@@ -157,7 +157,6 @@ function loopProbe({ probe, notifications }: loopProbeParams) {
   const flags = getContext().flags
   // flags is the monika parameter flags... these are used:
```
Comment (sapiderman) [inline src/looper/index.ts:158]: I think we dont need these comments anymore. we can cleanup and erase this?

**Review by sapiderman — APPROVED** [review]
LGTM 
:coffee: :tea: :milk_glass:

File: src/looper/index.ts (hunk 1 above)
Comment (kevin-hyperjump) [reply src/looper/index.ts:158]: Sure, I'll remove them.

**Review by nicnocquee — APPROVED** [review]
