### PR TITLE
fix: not send recovery status when running on Symon mode

### LINKED ISSUE #583: Not send recovery status when running on Symon mode
Step to reproduce:

1. Run your test website (Any website you can start and stop, E.g: create-react-app)
2. Run Monika on Symon mode (make sure you have a test website probe in Symon)
3. Shutdown your website (Monika will send incident status)
4. Re-run your test website (And you will see Monika doesn't send recovery status)

### PR DESCRIPTION
**Pull request by kevin-hyperjump**
Fixes #583

### CODE REVIEW

**Review by nicnocquee — APPROVED** [review]

File: src/components/config/parse-postman.ts [hunk 1]
```diff
@@ -35,14 +35,15 @@ const getConvertedProbeFromPostmanItem = (item: any) => {
...
+        id: req.name,
         url: req.url.raw,
         method: req.method,
         headers: req?.header?.reduce(
           (obj: any, it: any) => Object.assign(obj, { [it.key]: it.value }),
           {}
         ),
         body: req?.body?.raw || JSON.parse('{}'),
-        timeout: 10000,
+        timeout: 10_000,
```
Comment (dennypradipta) [inline src/components/config/parse-postman.ts:46]: What's the meaning of the underscore?

Comment (nicnocquee) [reply src/components/config/parse-postman.ts:46]: In TS2.7, you can add separators in a number so it's easier to read. https://mariusschulz.com/blog/numeric-separators-in-typescript

**Review by dennypradipta — APPROVED** [review]
