### PR TITLE
Fix: #384 chain request header is not set on chaining request

### LINKED ISSUE #384: Headers value is not changed for chaining request
**Describe the bug**
Headers value is not replaced after tried to assigned it with response value from chaining requests.

**To Reproduce**
1. Create a chaining requests configuration
2. Assign value to the header of second request from the response of first request. e.g
```
"requests":[
        { 
          "url": "http://127.0.0.1/v1/firstRequest",
          "method": "GET",
          "timeout": 6000
        },
        {
          "url": "http://127.0.0.1/v1/secondrequests",
          "method": "GET",
          "timeout": 6000,
          "headers": {
            "Authorization": "{{ responses.[0].data.token }}"
          }
        }
      ],
```
3. run monika using this config
4. See error on the second request

**Expected behavior**
second request should be successfully run and return success status

**Screenshots**
Screen Shot 2021-09-07 at 16 28 16

**Desktop (please complete the following information):**
 - OS: [MacOs]
 - Version [11.4]

### PR DESCRIPTION
**Pull request by ilmiawan**
# Monika Pull Request (PR)  
Fix #384 Header value is not changed

## What feature/issue does this PR add  
Fix headers value not set on second requests on chain-request process.

## How did you implement / how did you fix it  
set directly the replaced value using Handlebars to requestConfig headers object

## How to test  
1. set chain-request config
2. set header of second request value from first request response
3. run monika using the chain request config
4. second request should send the right header value and return 200 response status

## image 
Screen Shot 2021-09-07 at 16 58 09

### CODE REVIEW

File: src/components/probe/probing.ts [hunk 1]
```diff
@@ -41,20 +41,19 @@ export async function probing(
...
 
-          headers = {
-            ...headers,
+          requestConfig.headers = {
+            ...requestConfig.headers,
             [header]: renderedHeader,
           }
         } catch (_) {
-          headers = { ...headers }
+          requestConfig.headers = { ...requestConfig.headers }
```
Comment (nicnocquee) [inline src/components/probe/probing.ts:56]: is this line really necessary? i think this does nothing, doesn't it?

**Review by gsukanto — APPROVED** [review]

File: src/components/probe/probing.ts (hunk 1 above)
Comment (ilmiawan) [reply src/components/probe/probing.ts]: done

**Review by dennypradipta — APPROVED** [review]

**Review by nicnocquee — APPROVED** [review]
